# Generated by Django 5.1 on 2024-08-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisan', models.CharField(max_length=30)),
                ('mode_of_work', models.TextField(blank=True)),
                ('location', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('description', models.TextField()),
            ],
        ),
    ]
