# Generated by Django 5.1 on 2024-08-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='job',
            name='price',
            field=models.TextField(),
        ),
    ]
